[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Aerostack2"
authors = [{name = "Miguel Fernandez Cortizas", email = "miguel.fernandez.cortizas@upm.es"}]
dynamic = ["version", "description"]
